services:
  jupyterq:
    image: jupyterq
    build: .
    container_name: jupyterq
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - ./kc.lic:/home/kx/kc.lic
      - ./notebooks:/home/kdb/notebooks
